- name: Simulate Empty File Upload to Trigger Content-Length Error
  run: |
    echo "Simulating empty file upload to trigger Content-Length error."
    
    # Ensure the directory exists
    mkdir -p large-files
    
    # Create an empty file
    touch large-files/empty-file.mp4
    
    # Check if file is created
    if [ ! -f "large-files/empty-file.mp4" ]; then
      echo "File not found!"
      exit 1
    fi
    
    # Now we will upload the empty file, omitting the Content-Length option
    echo "Uploading the empty file without Content-Length header"
    
    # Attempt to upload the empty file to simulate the MissingContentLength error
    oci os object put \
      --namespace $OCI_NAMESPACE \
      --bucket-name $OCI_BUCKET \
      --file large-files/empty-file.mp4 \
      --name empty-file.mp4 \
      --force

    echo "File uploaded (or failed) to OCI bucket"
